changed get request to post
openfoodfacts/openfoodfacts-dart pull request #415
Opened 2022-03-16 07:50 UTC by AshAman999

### What
- migrating all the get requests to post

### Screenshot
(Insert a screenshot to provide visual record of your changes, if visible)
### Fixes bug(s)
- #354 and #414 
### Part of 
- #407 
(please be as granular as possible)

2022-03-16 08:03 UTC, AshAman999 commented
@monsieurtanuki  I have done the task,please review the changes,
It's my 1st  pr in this organization so sorry if any incompleteness is found in the code.

2022-03-16 17:51 UTC, monsieurtanuki reviewed
It looks OK @AshAman999 except that for some reason the unit tests did not start.
Besides, you missed at least one `addUserAgentParameters: false`: I suggest that you create a new method `static Uri UriHelper.getPostUri(final String path, {final QueryType? queryType,})` and use it in at least the 15 times where `UriHelper.getUri` is used.

2022-03-16 17:51 UTC, monsieurtanuki commented on lib/openfoodfacts.dart
>        queryType: queryType,
What about `addUserAgentParameters: false,`?

2022-03-16 18:29 UTC, AshAman999 commented
@monsieurtanuki  please have a look, i guess this would be okay now

2022-03-17 08:37 UTC, monsieurtanuki requested changes
Hi @AshAman999!
The code looks rather OK, but have a look at my comments: there are things to fix.
Anyway the tests didn't pass: don't forget to run the tests locally (`dart test`) before updating your PR.

2022-03-17 14:05 UTC, monsieurtanuki approved these changes
Looks good now, thank you @AshAman999!

2022-03-18 06:34 UTC, merged

2022-03-18 06:35 UTC, monsieurtanuki commented
Congratulations @AshAman999 for your first PR here!