feat: Integrate all routes from nutripatrol's API
openfoodfacts/openfoodfacts-dart pull request #991
Opened 2024-11-13 10:58 UTC by Valimp

### What
Add nutripatrol's routes to the dart SDK

### Fixes bug(s)
#885

2024-11-13 16:06 UTC, monsieurtanuki reviewed
Hi @Valimp!
Please have a look at my comments.

2024-11-13 16:06 UTC, monsieurtanuki commented on lib/src/nutripatrol/create_flag.dart
> +enum Source {
Please use a less ambiguous name like NutripatrolSource.

2024-11-13 16:06 UTC, monsieurtanuki commented on lib/src/nutripatrol/create_flag.dart
> +enum Flavor {
We already have a Flavor: please reuse it.

2024-11-13 16:06 UTC, monsieurtanuki commented on lib/src/nutripatrol/get_ticket.dart
> +enum TicketType {
Isn't that the same "Type"?

2024-11-13 16:06 UTC, monsieurtanuki commented on lib/src/nutripatrol/get_ticket.dart
> +enum Flavor {
Don't repeat that already repeated code.

2024-11-13 16:06 UTC, monsieurtanuki commented on lib/src/nutripatrol_api_client.dart
> +    final TicketType type_ = TicketType.image,
type_ ?

2025-01-10 12:23 UTC, monsieurtanuki requested changes
Hi @Valimp!
The code must pass the analysis tests.

2025-01-10 17:08 UTC, g123k commented
@Valimp will have his midterms next week, that's why I've fixed the main warnings.
However the enum `NutripatrolSource` is declared twice.

Other than that, I think you can review the PR @monsieurtanuki

2025-01-10 18:07 UTC, monsieurtanuki commented
> @Valimp will have his midterms next week
> Other than that, I think you can review the PR

@g123k As you may know currently I don't have a computer, so code reviews are sometimes acrobatic and I don't want to review too often.
Besides, I already had a quick look at the code and I saw several things to fix. If @Valimp is busy, I don't see the point of reviewing now instead of when @Valimp is available.
Unless you're in a hurry and want to fix the code yourself.

2025-01-28 18:07 UTC, monsieurtanuki reviewed
Hi @Valimp!
Please have a look at my comments.

2025-01-28 18:07 UTC, monsieurtanuki commented on lib/src/nutripatrol_api_client.dart
> +        uriHelper: uriHelper, bearerToken: "");
`bearerToken: ""`? I don't think so.
Please consider using `doPostRequest`.
If you really need `doPostJsonRequest`, you'll have to do something cleaner, like an explicit `String? bearerToken`.

2025-01-28 18:07 UTC, monsieurtanuki commented on lib/src/nutripatrol_api_client.dart
> +    assert(ticketId >= 0, "The id must be >= 0");
Please remove assert.

2025-01-28 18:07 UTC, monsieurtanuki commented on lib/src/nutripatrol_api_client.dart
> +      'status': status.toString().split('.').last,
cf OffTagged.

2025-01-28 18:07 UTC, monsieurtanuki commented on lib/src/nutripatrol/create_flag_request.dart
> +  late String type;
List of values into an enum?

2025-01-28 18:07 UTC, monsieurtanuki commented on lib/src/nutripatrol/create_flag_request.dart
> +  late String source;
Isn't there an enum for that?

2025-01-28 18:07 UTC, monsieurtanuki commented on lib/src/nutripatrol/create_flag_request.dart
> +  late String flavor;
There's an enum for that.

2025-01-28 18:07 UTC, monsieurtanuki commented on lib/src/nutripatrol/create_flag_request.dart
> +  String? reason;
Is there a list of values or is it free text?

2025-01-28 18:07 UTC, monsieurtanuki commented on lib/src/nutripatrol/create_flag.dart
> +  late String type;
List of values?

2025-01-28 18:07 UTC, monsieurtanuki commented on lib/src/nutripatrol/create_flag.dart
> +  late String source;
List of values?

2025-01-28 18:07 UTC, monsieurtanuki commented on lib/src/nutripatrol/create_flag.dart
> +  late String flavor;
There's an enum for that.

2025-01-28 18:07 UTC, monsieurtanuki commented on lib/src/nutripatrol/create_flag.dart
> +  @JsonKey(name: 'created_at')
You probably need method to/from json.

2025-02-08 15:56 UTC, monsieurtanuki reviewed
Hi @Valimp!
Please have a look at my comments.

2025-02-08 15:56 UTC, monsieurtanuki commented on test/api_nutripatrol_create_flag.dart
> +      final MaybeError<CreateNutripatrolFlag> response =
You're about to store junk in your production server.
I would definitely recommend using a test server.

2025-02-08 15:56 UTC, monsieurtanuki commented on test/api_nutripatrol_create_flag.dart
> +  setUpAll(() {
We don't use it in the other tests. Do you really need it? If so please add a specific comment.

2025-02-08 15:56 UTC, monsieurtanuki commented on lib/src/utils/nutripatrol_types.dart
> +enum NutripatrolSource {
I would
* extend `OffTagged`
* put each `enum` in a specific file
* add "Nutripatrol" and remove "Enum" in your comments

But that's not mandatory.

2025-02-08 15:56 UTC, monsieurtanuki commented on lib/src/nutripatrol_api_client.dart
> +          'reason': reason.toString().split('.').last,
No

2025-02-08 15:56 UTC, monsieurtanuki commented on lib/src/nutripatrol_api_client.dart
> +          'type': type.toString().split('.').last,
No

2025-02-08 15:56 UTC, monsieurtanuki commented on lib/src/nutripatrol_api_client.dart
> +          'source': source.toString().split('.').last,
No. Either `.name` or `.offTag`.

2025-02-08 15:56 UTC, monsieurtanuki commented on lib/src/nutripatrol_api_client.dart
> +    queryParameters['type_'] = type.toString().split('.').last;
No.

2025-02-08 15:56 UTC, monsieurtanuki commented on lib/src/nutripatrol/get_tickets.dart
> +@JsonSerializable()
Please add a `///` comment for the class too.

2025-02-08 15:56 UTC, monsieurtanuki commented on lib/src/nutripatrol/get_tickets.dart
> +  /// Max Page
What is a "max page"?

2025-02-08 15:56 UTC, monsieurtanuki commented on lib/src/nutripatrol/get_ticket.dart
> +import 'package:openfoodfacts/openfoodfacts.dart';
Please remove that line.

2025-02-08 15:56 UTC, monsieurtanuki commented on lib/src/nutripatrol/get_ticket.dart
> +import 'package:openfoodfacts/src/utils/nutripatrol_types.dart';
```suggestion
import '../utils/nutripatrol_types.dart';
```

2025-02-08 15:56 UTC, monsieurtanuki commented on lib/src/utils/nutripatrol_types.dart
Would make sense in folder `nutripatrol`.

2025-02-08 15:56 UTC, monsieurtanuki commented on lib/src/nutripatrol/get_ticket.dart
> +  @JsonKey(name: 'created_at')
Would you please confirm that it does work and that you don't need `stringTimestampToDate`?
If so that's good news, we would also remove calls to `stringTimestampToDate` from other parts of the code.

2025-02-08 15:56 UTC, monsieurtanuki commented on lib/openfoodfacts.dart
And `nutripatrol_types.dart`

2025-02-08 15:56 UTC, monsieurtanuki commented on lib/src/model/old_product_result.g.dart
No, you should NOT change that file, please.

2025-02-08 15:56 UTC, monsieurtanuki commented on lib/src/nutripatrol/create_flag.dart
> +@JsonSerializable()
Please add a `///` comment for the class too.

2025-02-08 15:56 UTC, monsieurtanuki commented on lib/src/nutripatrol/get_flag.dart
> +  late DateTime createdAt;
cf. other comment about `DateTime` and `stringTimestampToDate`.
Besides, I would prefer `created`, as in the rest of the package.

2025-02-08 15:56 UTC, monsieurtanuki commented on test/api_nutripatrol_create_flag.dart
You should test the other methods of Nutripatrol.
For instance, list the tickets and find the one you've just created.

2025-02-09 07:41 UTC, teolemon commented on test/api_nutripatrol_create_flag.dart
> +      final MaybeError<CreateNutripatrolFlag> response =
We don't have a preprod for nutripatrol

2025-02-09 08:25 UTC, monsieurtanuki commented on test/api_nutripatrol_create_flag.dart
> +      final MaybeError<CreateNutripatrolFlag> response =
> We don't have a preprod for nutripatrol

We'll see if the prod gets very messy, then.

2025-03-04 15:34 UTC, teolemon commented
@monsieurtanuki @g123k can we finally merge this ?

2025-03-05 14:13 UTC, monsieurtanuki commented on lib/src/model/old_product_result.g.dart
Please keep the comment as it was.

2025-03-05 14:16 UTC, monsieurtanuki commented on lib/src/nutripatrol_api_client.dart
> +    return MaybeError<CreateNutripatrolFlag>.responseError(response);
Please use `try` / `catch` for all your `MaybeError` statements, cf. prices.

2025-03-05 14:17 UTC, monsieurtanuki commented
> @monsieurtanuki @g123k can we finally merge this ?

@teolemon Quickly said: no.

* there are many unresolved conversations
* in the enum types (`nutripatrol_types.dart`) a `label` field has been introduced instead of the widely used (and suggested) `offTag`
* there are a couple of unwanted lines to remove in `old_product_result.g.dart` - this file isn't supposed to change, the specific comment is meant to be kept
* I suspect that `nutripatrol_types.dart` isn't exported
* suggested tests are missing, like testing if whatever we created can be retrieved afterwards

2025-10-08 07:01 UTC, monsieurtanuki commented
@Valimp Still working on it?

2025-10-08 09:54 UTC, g123k commented
> @Valimp Still working on it?

No, @Valimp completed his apprenticeship.

2025-10-08 10:20 UTC, monsieurtanuki commented
> No, @Valimp completed his apprenticeship.

Good opportunity to learn that even if you work hard on a PR, sometimes it doesn't get merged.
Second lesson: we'd be better off starting a new PR from scratch.

Closing...

2025-10-08 10:20 UTC, closed without merging